---
language: node_js
node_js:
  - "12"

dist: bionic

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master

script:
  - yarn ci

# @TODO Turn back after coveralls and codacy implementation are fixed
#after_script:
#  - yarn coveralls
#  - yarn codacy-coverage
